erc721: add setBaseURI
gochain/contracts pull request #2
Opened 2021-04-13 14:15 UTC by jmank88

This PR adds a `setBaseURI` function requiring `DEFAULT_ADMIN_ROLE`.

@r-gochain How did you generate these before? I just ran `web3 contract build GenericERC721.sol` from inside `./erc721`, and left the extra files not added to git. Does this look right? (bin by character diff looks very similar)

2021-04-13 15:00 UTC, treeder requested changes

2021-04-13 15:00 UTC, treeder commented on erc721/GenericERC721.sol
> +        require(hasRole(DEFAULT_ADMIN_ROLE, _msgSender()), "web3 CLI: must have admin role to update tokenURI");
```suggestion
        require(hasRole(DEFAULT_ADMIN_ROLE, _msgSender()), "must have admin role to update baseURI");
```

2021-04-13 19:15 UTC, r-gochain commented
Generated using latest web3, updated the constructor to support additional arguments (symbol and name), that's all

2021-04-14 15:02 UTC, jmank88 commented
Anything else to change here?

2021-04-14 15:07 UTC, treeder approved these changes

2021-04-14 15:07 UTC, merged